### ISSUE TITLE
Comparing two complex object returns an exception

### ISSUE THREAD

**Issue by sekulicb** [replaysMike/AnyClone#10]
Hi. I have a fairly complex objects to compare. Its basically Dictionary<string, object>, where the number of keys inside dictionary is 23. Some are plain strings, some are Boolean, but some are StrokeCollection, List< CustomTypeDTO >, OtherCustomTypeDTO etc...you get the point, its all there 😄 

I'm using FastDeepCloner currently to create snapshot for some of the properties that are collections, because AnyClone also throws exception, something like: "Type is ambiguous". So after the snapshot of some properties, the original object and the one with snapshot properties are compared using AnyDiff. I get the following exception:

**Sequence contains no matching element**

Stack trace: 

 at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at TypeSupport.Extensions.TypeExtensions.GetExtendedProperty(Type type, String name, Type declaringType)
   at TypeSupport.ExtendedField..ctor(FieldInfo fieldInfo)
   at TypeSupport.ExtendedField.op_Implicit(FieldInfo fieldInfo)
   at TypeSupport.Extensions.TypeExtensions.<>c.<GetFields>b__1_0(FieldInfo x)
   at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at TypeSupport.Extensions.TypeExtensions.GetFields(Type type, FieldOptions options)
   at TypeSupport.Extensions.TypeExtensions.GetFields(Type type, FieldOptions options)
   at AnyDiff.DiffProvider.RecurseProperties(Object left, Object right, Object parent, List`1 differences, Int32 currentDepth, Int32 maxDepth, ObjectHashcodeMap objectTree, String path, ComparisonOptions comparisonOptions, ICollection`1 propertyList, DiffOptions diffOptions)
   at AnyDiff.DiffProvider.GetDifferences(String propertyName, Type propertyType, TypeConverter typeConverter, Object left, Object right, Object parent, List`1 differences, Int32 currentDepth, Int32 maxDepth, ObjectHashcodeMap objectTree, String path, ComparisonOptions options, ICollection`1 propertyList, DiffOptions diffOptions)
   at AnyDiff.DiffProvider.RecurseProperties(Object left, Object right, Object parent, List`1 differences, Int32 currentDepth, Int32 maxDepth, ObjectHashcodeMap objectTree, String path, ComparisonOptions comparisonOptions, ICollection`1 propertyList, DiffOptions diffOptions)
   at AnyDiff.DiffProvider.ComputeDiff[T](T left, T right, Int32 maxDepth, ComparisonOptions comparisonOptions, DiffOptions diffOptions, Expression`1[] propertyList)
   at AnyDiff.Extensions.Extensions.Diff[T](T left, T right, Int32 maxDepth, ComparisonOptions comparisonOptions, DiffOptions diffOptions, Expression`1[] propertyList)
   at AnyDiff.Extensions.Extensions.Diff[T](T left, T right, Expression`1[] propertyList)

**Comment by sekulicb** [comment]
As for the AnyClone exception:

**Ambiguous match found.**

Stack trace:

at System.RuntimeType.GetMethodImplCommon(String name, Int32 genericParameterCount, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.RuntimeType.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConv, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name, BindingFlags bindingAttr)
   at AnyClone.CloneProvider`1.InspectAndCopy(Object sourceObject, Int32 currentDepth, Int32 maxDepth, CloneOptions options, IDictionary`2 objectTree, String path, ICollection`1 ignorePropertiesOrPaths)
   at AnyClone.CloneProvider`1.InspectAndCopy(Object sourceObject, Int32 currentDepth, Int32 maxDepth, CloneOptions options, IDictionary`2 objectTree, String path)
   at AnyClone.CloneProvider`1.Clone(T sourceObject, CloneOptions options)
   at AnyClone.Cloner.Clone[T](T sourceObject, CloneOptions options)
   at AnyClone.Cloner.Clone[T](T sourceObject)

**Comment by sekulicb** [comment]
I solved this by comparing each value by key in two foreach loops, so everything works. Although not ideal, for now will suffice.
