### ISSUE TITLE
Cannot set initonly static field 'Invariant' after type 'System.Globalization.CompareInfo' is initialized. Cannot set initonly static field 'ValueType' after type 'System.RuntimeType' is initialized.

### ISSUE THREAD

**Issue by xlievo** [replaysMike/AnyClone#9]
at System.RuntimeFieldHandle.SetValue(RtFieldInfo field, Object obj, Object value, RuntimeType fieldType, FieldAttributes fieldAttr, RuntimeType declaringType, Boolean& domainInitialized)
   at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at System.Reflection.FieldInfo.SetValue(Object obj, Object value)
   at TypeSupport.Extensions.ObjectExtensions.SetFieldValue(Object obj, FieldInfo field, Object valueToSet)
   at AnyClone.CloneProvider`1.InspectAndCopy(Object sourceObject, Int32 currentDepth, Int32 maxDepth, CloneOptions options, IDictionary`2 objectTree, String path, ICollection`1 ignorePropertiesOrPaths)
   at AnyClone.CloneProvider`1.InspectAndCopy(Object sourceObject, Int32 currentDepth, Int32 maxDepth, CloneOptions options, IDictionary`2 objectTree, String path, ICollection`1 ignorePropertiesOrPaths)
   at AnyClone.CloneProvider`1.InspectAndCopy(Object sourceObject, Int32 currentDepth, Int32 maxDepth, CloneOptions options, IDictionary`2 objectTree, String path, ICollection`1 ignorePropertiesOrPaths)
   at AnyClone.CloneProvider`1.InspectAndCopy(Object sourceObject, Int32 currentDepth, Int32 maxDepth, CloneOptions options, IDictionary`2 objectTree, String path, ICollection`1 ignorePropertiesOrPaths)
   at AnyClone.CloneProvider`1.InspectAndCopy(Object sourceObject, Int32 currentDepth, Int32 maxDepth, CloneOptions options, IDictionary`2 objectTree, String path, ICollection`1 ignorePropertiesOrPaths)
   at AnyClone.CloneProvider`1.InspectAndCopy(Object sourceObject, Int32 currentDepth, Int32 maxDepth, CloneOptions options, IDictionary`2 objectTree, String path)
   at AnyClone.CloneProvider`1.Clone(T sourceObject, CloneOptions options)
   at AnyClone.Cloner.Clone[T](T sourceObject, CloneOptions options)
   at AnyClone.Cloner.Clone[T](T sourceObject)

**Comment by xlievo** [comment]
Seems to throw an exception to System.Type
